version: '3.3'

networks:
  network_divvy:
    external: true

services:
  api.divvy.com:
    image: trinsiclabs/divvy-api:latest
    container_name: api.divvy.com
    user: node
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
    volumes:
      - ./src/:/home/node/app
      - ./wallet/:/home/node/wallet
      - ../network/org-config/:/home/node/org-config
    working_dir: /home/node/app
    command: sh -c 'npm install && npm start'
    networks:
      - network_divvy
